In [1]:
import torch
#Directly from data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [2]:
# From Numpy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [3]:
# From other tensors
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5312, 0.7504],
        [0.1213, 0.8396]]) 



In [4]:
# Populating tensors with random/constant values

shape = (2, 3,) # tuple of tensor dimensions
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
torch.manual_seed(1789)
rand_tensor = torch.rand(shape)
empty_tensor = torch.empty(shape) # memory is allocated, tensor populated with garbage- values
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")
print(f"Empty Tensor: \n {empty_tensor}")


Random Tensor: 
 tensor([[0.9631, 0.4014, 0.7564],
        [0.5782, 0.5438, 0.1929]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
Empty Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.empty(2, 2, 3)
print(x.shape,"\n")
print(x)

torch.Size([2, 2, 3]) 

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [6]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.float64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int8)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int32)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.int64)
print(a.dtype)
a = torch.ones((2, 3), dtype=torch.bool)
print(a.dtype)


torch.int16
torch.float64
torch.int8
torch.int32
torch.int64
torch.bool


In [7]:
# Create a tensor
tensor = torch.rand(3, 2)
print(f"Device tensor is initially stored on: {tensor.device}")



Device tensor is initially stored on: cpu


In [8]:
# Check if GPU is available and move tensor to GPU if it is
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
    print(f"Device tensor is now stored on: {tensor.device}")
else:
    print("CUDA is not available. Tensor remains on CPU.")

CUDA is not available. Tensor remains on CPU.


In [9]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}","\n")
print(f"First column: {tensor[:, 0]}","\n")
print(f"Last column: {tensor[:, -1]}","\n")
tensor[:,1] = 0 # set all elements in second column to 0
print(tensor)


First row: tensor([1., 1., 1., 1.]) 

First column: tensor([1., 1., 1., 1.]) 

Last column: tensor([1., 1., 1., 1.]) 

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
ones = torch.zeros(2, 2) + 1 # adding 1 to a tensor of zeros
twos = torch.ones(2, 2) * 2 # multiplying a tensor of ones by 2
threes = (torch.ones(2, 2) * 7 - 1) / 2 # chaining operations
fours = twos ** 2 # squaring a tensor
sqrt2s = twos ** 0.5 # square root of a tensor

print(ones,"\n")
print(twos,"\n")
print(threes,"\n")
print(fours,"\n")
print(sqrt2s,"\n")


tensor([[1., 1.],
        [1., 1.]]) 

tensor([[2., 2.],
        [2., 2.]]) 

tensor([[3., 3.],
        [3., 3.]]) 

tensor([[4., 4.],
        [4., 4.]]) 

tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]]) 



In [11]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]]) # element-wise exponentiation
print(powers2,"\n")
fives = ones + fours # element-wise addition
print(fives,"\n")
dozens = threes * fours # element-wise multiplication
print(dozens,"\n")

tensor([[ 2.,  4.],
        [ 8., 16.]]) 

tensor([[5., 5.],
        [5., 5.]]) 

tensor([[12., 12.],
        [12., 12.]]) 



In [12]:
rand = torch.rand(2, 4) # random tensor
doubled = rand * (torch.ones(1, 4) * 2) # broadcasting
print(rand)
print(doubled)


tensor([[0.2569, 0.8153, 0.3774, 0.6209],
        [0.8973, 0.6783, 0.8594, 0.6721]])
tensor([[0.5138, 1.6306, 0.7549, 1.2419],
        [1.7946, 1.3567, 1.7187, 1.3442]])


In [13]:
a = torch.ones(4, 3, 2)
b = a * torch.rand(3, 2)
print(b, "\n") # 3rd & 2nd dims identical to a, dim 1 absent
c = a * torch.rand(4, 1, 2)
print(c, "\n") # 3rd dim = 1, 2nd dim identical to a
d = a * torch.rand(1, 3, 2)
print(d, "\n") # 3rd dim identical to a, 2nd dim = 1


tensor([[[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]],

        [[0.4544, 0.6353],
         [0.5914, 0.9689],
         [0.5715, 0.7136]]]) 

tensor([[[0.4606, 0.7056],
         [0.4606, 0.7056],
         [0.4606, 0.7056]],

        [[0.5921, 0.0557],
         [0.5921, 0.0557],
         [0.5921, 0.0557]],

        [[0.3866, 0.2989],
         [0.3866, 0.2989],
         [0.3866, 0.2989]],

        [[0.8993, 0.2320],
         [0.8993, 0.2320],
         [0.8993, 0.2320]]]) 

tensor([[[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]],

        [[0.2450, 0.1956],
         [0.8150, 0.1024],
         [0.2813, 0.7884]]]) 

In [14]:
import math

a = torch.rand(2, 4) * 2 - 1 # random tensor in range [-1, 1]
print(torch.abs(a),"\n") #absolute value
print(torch.ceil(a),"\n") #ceiling
print(torch.floor(a),"\n") #floor
print(torch.clamp(a, -0.5, 0.5)) #clamping: values < -0.5 set to -0.5, values > 0.5 set to 0.5


tensor([[0.8933, 0.1511, 0.7021, 0.4549],
        [0.2857, 0.2995, 0.6397, 0.6817]]) 

tensor([[-0., -0., -0., -0.],
        [1., -0., 1., -0.]]) 

tensor([[-1., -1., -1., -1.],
        [ 0., -1.,  0., -1.]]) 

tensor([[-0.5000, -0.1511, -0.5000, -0.4549],
        [ 0.2857, -0.2995,  0.5000, -0.5000]])


In [15]:
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4]) # angles in radians
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles,"\n")
print(sines,"\n")
print(inverses,"\n")



Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562]) 

tensor([0.0000, 0.7071, 1.0000, 0.7071]) 

tensor([0.0000, 0.7854, 1.5708, 0.7854]) 



In [16]:
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))


tensor([3, 2, 1])


In [17]:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
print(d,"\n")
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(e,"\n")
print(torch.eq(d, e))  # returns a tensor of type bool



Broadcasted, element-wise equality comparison:
tensor([[1., 2.],
        [3., 4.]]) 

tensor([[1., 1.]]) 

tensor([[ True, False],
        [False, False]])


In [18]:
d = torch.tensor([[1., 2.], [3., 4.]])
print(torch.max(d))
print(torch.max(d).item())
print(torch.mean(d))
print(torch.std(d))
print(torch.prod(d))
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2])))  # filter unique elements


tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])


In [19]:
v1 = torch.tensor([1., 0., 0.])  # x unit vector
v2 = torch.tensor([0., 1., 0.])  # y unit vector

print(torch.cross(v1, v2),"\n")  # returns cross product of vectors v1 and v2

m1 = torch.rand(2, 2)  # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]])  # three times identity matrix
print(m1,"\n")
m3 = torch.matmul(m1, m2)  # same as m3 = m1@m2
print(m3,"\n")
print(torch.svd(m3),"\n")  # singular value decomposition


tensor([0., 0., 1.]) 

tensor([[0.0902, 0.7986],
        [0.4120, 0.8499]]) 

tensor([[0.2705, 2.3959],
        [1.2360, 2.5498]]) 

torch.return_types.svd(
U=tensor([[-0.6444, -0.7647],
        [-0.7647,  0.6444]]),
S=tensor([3.6687, 0.6192]),
V=tensor([[-0.3051,  0.9523],
        [-0.9523, -0.3051]])) 



C:\Users\dhanu\AppData\Local\Temp\ipykernel_15952\3018723044.py:4: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\Cross.cpp:66.)
  print(torch.cross(v1, v2),"\n")  # returns cross product of vectors v1 and v2


In [20]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))  # this operation creates a new tensor in memory
print(a)  # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)  # b has changed


a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [21]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)
print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)


Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.5300, 0.3159],
        [0.7081, 0.1727]])

After adding:
tensor([[1.5300, 1.3159],
        [1.7081, 1.1727]])
tensor([[1.5300, 1.3159],
        [1.7081, 1.1727]])
tensor([[0.5300, 0.3159],
        [0.7081, 0.1727]])

After multiplying
tensor([[0.2809, 0.0998],
        [0.5014, 0.0298]])
tensor([[0.2809, 0.0998],
        [0.5014, 0.0298]])


In [22]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)
print(c,"\n")
d = torch.matmul(a, b, out=c)
print(c,"\n") # contents of c have changed

assert c is d # test c & d are same object, not just containing equal values # make sure that our new c is the same object as the old one
assert id(c) == old_id

torch.rand(2, 2, out=c) # works for creation too!
print(c,"\n") # c has changed again

assert id(c) == old_id # still the same object!


tensor([[0., 0.],
        [0., 0.]]) 

tensor([[0.4621, 0.5195],
        [0.1035, 0.1086]]) 

tensor([[0.7443, 0.7234],
        [0.7417, 0.6321]]) 



In [23]:
a = torch.tensor([1, 2, 3, 4])
a_reshaped = torch.reshape(a, (2, 2))
print(a_reshaped,"\n")

b = torch.rand(56, 56)  # Consider 56x56 image
c = b.unsqueeze(0)  # unsqueeze(i) adds dimension of length 1 at index i
print(c,"\n")  # c is now a batch of 1 image of shape 56x56

d = torch.rand(1, 20)
print(d.shape,"\n")
e = d.squeeze(0)  # squeeze(i) removes a dimension if shape[i] is 1
print(e.shape,"\n")

x, y, z = torch.rand(2, 3), torch.rand(2, 3), torch.rand(2, 3)
cat_tensor = torch.cat((x, y, z), dim=0)  # concatenates tensors along rows
print(cat_tensor)


tensor([[1, 2],
        [3, 4]]) 

tensor([[[0.2893, 0.1629, 0.1285,  ..., 0.2148, 0.4567, 0.4887],
         [0.4287, 0.6620, 0.0410,  ..., 0.0035, 0.2118, 0.5679],
         [0.5858, 0.9733, 0.3692,  ..., 0.6938, 0.0219, 0.6840],
         ...,
         [0.7916, 0.7293, 0.6940,  ..., 0.1591, 0.5954, 0.1723],
         [0.3036, 0.3075, 0.0482,  ..., 0.1157, 0.1832, 0.4325],
         [0.0244, 0.9426, 0.9898,  ..., 0.9208, 0.1439, 0.2637]]]) 

torch.Size([1, 20]) 

torch.Size([20]) 

tensor([[0.2854, 0.0043, 0.2710],
        [0.6577, 0.9595, 0.6804],
        [0.7525, 0.3462, 0.6816],
        [0.7475, 0.8048, 0.6805],
        [0.6754, 0.7080, 0.1422],
        [0.7200, 0.5164, 0.3350]])


In [24]:
a = torch.ones(2, 2)
b=a
a[0][1] = 561 # we change a...
print(b) # ...and b is also altered


tensor([[  1., 561.],
        [  1.,   1.]])


In [25]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a # different objects in memory...
print(torch.eq(a,b)) # ...but still with the same contents!
a[0][1] = 561 # a changes...
print(b)   # ...but b is still all ones


tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


In [26]:
if torch.cuda.is_available():
    print('We have a GPU!')
else:
    try:
        device = torch.device("mps")
        print("MPS available!")
    except:
        print('Sorry, CPU only.')


MPS available!


In [27]:
import numpy as np
import torch

# Creating a NumPy array
numpy_array = np.ones((2, 3))
print("NumPy Array:")
print(numpy_array)

# Converting NumPy array to PyTorch tensor
pytorch_tensor = torch.from_numpy(numpy_array)
print("\nPyTorch Tensor:")
print(pytorch_tensor)

# Creating a random PyTorch tensor
pytorch_rand = torch.rand(2, 3)
print("\nRandom PyTorch Tensor:")
print(pytorch_rand)

# Converting PyTorch tensor to NumPy array
numpy_rand = pytorch_rand.numpy()
print("\nConverted NumPy Array:")
print(numpy_rand)

# Changes to NumPy array reflect in the PyTorch tensor and vice versa
numpy_array[1, 1] = 23
print("\nUpdated PyTorch Tensor from NumPy Array:")
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print("\nUpdated NumPy Array from PyTorch Tensor:")
print(numpy_rand)


NumPy Array:
[[1. 1. 1.]
 [1. 1. 1.]]

PyTorch Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

Random PyTorch Tensor:
tensor([[0.1107, 0.1027, 0.5759],
        [0.5720, 0.0948, 0.9340]])

Converted NumPy Array:
[[0.11072505 0.10266209 0.5759023 ]
 [0.5719823  0.09482563 0.9340007 ]]

Updated PyTorch Tensor from NumPy Array:
tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)

Updated NumPy Array from PyTorch Tensor:
[[ 0.11072505  0.10266209  0.5759023 ]
 [ 0.5719823  17.          0.9340007 ]]


In [28]:
numpy_array[1, 1] = 23
print(pytorch_tensor,"\n")
pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64) 

[[ 0.11072505  0.10266209  0.5759023 ]
 [ 0.5719823  17.          0.9340007 ]]


In [29]:
# 1. Obtain a tensor containing only zeroes from the given tensor
pattern = torch.tensor([
    [1, 1, 1, 1],
    [1, 0, 0, 1],
    [1, 0, 0, 1],
    [1, 1, 1, 1]
])

# Only Zeros
z_tensor = pattern[pattern == 0]
print(z_tensor)

tensor([0, 0, 0, 0])


In [30]:
# 2. Create a Numpy array of shape (1,3,3) using PyTorch
import numpy as np

tensor = torch.randn(1, 3, 3) 
numpy_arr = tensor.numpy()
print(numpy_arr.shape)

(1, 3, 3)


In [31]:
# 3. Create two random (2,2,2) tensors and find the max, min, mean, std of their product (matrix multiplication)

tensor1 = torch.randn(2, 2, 2)
tensor2 = torch.randn(2, 2, 2)
prod = torch.matmul(tensor1, tensor2)
max_value = prod.max()
min_value = prod.min()
mean_value = prod.mean()
std_value = prod.std()

print("Product Tensor:\n", prod)
print("Max:", max_value.item())
print("Min:", min_value.item())
print("Mean:", mean_value.item())
print("Standard Deviation:", std_value.item())


Product Tensor:
 tensor([[[-1.3042, -1.9854],
         [ 0.7371,  1.1139]],

        [[ 0.8299, -0.2286],
         [-1.1302,  0.2267]]])
Max: 1.1138980388641357
Min: -1.9854429960250854
Mean: -0.2176162600517273
Standard Deviation: 1.141305923461914


In [32]:
# 4. Convert a 16x16 tensor into 1x256 tensor

tensor = torch.randn(16, 16)
reshape_tensor = tensor.view(1, 256)
print(reshape_tensor)
print(reshape_tensor.shape)


tensor([[ 1.2602,  0.5780,  0.5744, -0.9826,  0.1424, -1.8930,  0.9365,  0.8699,
         -0.8946, -0.9663, -0.2023, -0.2323, -0.4154, -1.0850, -0.0732,  1.0901,
         -0.7070, -0.8436,  0.9268, -0.1726, -0.2173,  0.4848, -0.1662,  0.4503,
         -0.0092,  1.5006,  0.7487,  0.6846, -0.5608, -0.4162, -0.1033,  0.1226,
          1.4508,  0.8665, -0.0797, -0.7292, -1.1314,  0.0778, -0.1277,  0.0503,
         -0.4481, -0.9796, -0.3960, -2.0513,  1.2842, -0.7467,  0.1248,  0.5606,
          0.1001,  0.5157, -0.1522, -1.9656,  1.0616,  0.1799,  1.3713,  1.0426,
          0.3672,  1.5418, -0.7915, -0.0170, -0.6112,  1.1928, -2.2906, -0.6567,
         -0.3279, -0.3063,  0.1272, -1.8845,  0.2662, -0.3030, -0.7385,  0.5151,
         -0.5311,  0.7734, -0.7320,  0.2891, -1.5840,  0.3405,  0.8430,  1.0413,
         -0.0503, -1.6872,  0.0707,  2.1473, -0.1485,  0.1352, -0.7820, -0.5942,
          1.0044,  0.2821, -0.0440,  0.7538, -0.4463,  0.2344, -1.4460,  0.1229,
         -1.3901, -0.0677,  

In [33]:
x = torch.randn(100, 1)
Y = 2*x + 1 + torch.randn(100, 1)*0.1
X = torch.cat([x, torch.ones_like(x)], dim=1)
coeffs = torch.inverse(X.t() @ X) @ X.t() @ Y
a, b = coeffs[0].item(), coeffs[1].item()
print(X,Y)
print(f"y = {a}x + {b}")

tensor([[-0.8973,  1.0000],
        [ 1.1153,  1.0000],
        [-0.4417,  1.0000],
        [-1.0744,  1.0000],
        [-1.4133,  1.0000],
        [-1.1884,  1.0000],
        [-1.2737,  1.0000],
        [-0.3490,  1.0000],
        [ 0.8529,  1.0000],
        [-0.6324,  1.0000],
        [ 0.3688,  1.0000],
        [-0.3774,  1.0000],
        [ 1.8798,  1.0000],
        [-0.6694,  1.0000],
        [ 0.5066,  1.0000],
        [-1.2047,  1.0000],
        [ 0.9593,  1.0000],
        [-1.6037,  1.0000],
        [-0.5977,  1.0000],
        [ 1.7874,  1.0000],
        [-0.7021,  1.0000],
        [ 0.0105,  1.0000],
        [ 0.2765,  1.0000],
        [ 0.8246,  1.0000],
        [ 1.2531,  1.0000],
        [ 0.7065,  1.0000],
        [-0.5122,  1.0000],
        [-0.0184,  1.0000],
        [-0.0538,  1.0000],
        [ 0.1870,  1.0000],
        [ 0.4142,  1.0000],
        [ 2.1545,  1.0000],
        [-0.6922,  1.0000],
        [-2.3479,  1.0000],
        [-1.2347,  1.0000],
        [ 0.0408,  1